### ISSUE TITLE
Data is not displayed anymore

### ISSUE THREAD

**Issue by tommartensen** [friedow/bpd#16]
Data from Sonarqube and Coveralls is not displayed anymore. If I navigate to the APIs manually, I can retrieve the data, the dashboard itself won't.

Chrome reports that it could be a CORS problem, instead I found out that both APIs are not available on OPTIONS method, so it might rather be a bug in the REST interface

**Comment by MaximilianV** [comment]
It indeed was a CORS problem (cors-anywhere wasn't running)
